# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-operativt-uppgiftslager
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

%dev.fullmakts.api.base-url=http://localhost:8080/someFullmaktsImplementation
%test.fullmakts.api.base-url=http://localhost:8080/someFullmaktsImplementation

kafka.oul_status_notification_topic_base=operativt-uppgiftslager-status-notification.

applikation=rimfrost-operativt-uppgiftslager
# Kafka configuration for outgoing channels

mp.messaging.outgoing.operativt-uppgiftslager-status-notification.connector=smallrye-kafka
mp.messaging.outgoing.operativt-uppgiftslager-status-notification.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Kafka broker configuration
# %dev.kafka.bootstrap.servers=127.0.0.1:9092
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}

quarkus.kafka.devservices.enabled=true

# quarkus.log.category."org.apache.kafka.clients.NetworkClient".level=ERROR

# Database configuration

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.database.default-schema=${quarkus.flyway.default-schema}
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.flyway.migrate-at-start=true
quarkus.flyway.create-schemas=true
quarkus.flyway.schemas=${quarkus.flyway.default-schema}
quarkus.flyway.default-schema=operativt_uppgiftslager

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

%dev.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.enabled=true

quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true