# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-operativt-uppgiftslager
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

%dev.fullmakts.api.base-url=http://localhost:8080/someFullmaktsImplementation
%test.fullmakts.api.base-url=http://localhost:8080/someFullmaktsImplementation

kafka.oul_status_notification_topic_base=operativt-uppgiftslager-status-notification.

applikation=rimfrost-operativt-uppgiftslager
# Kafka configuration for outgoing channels

mp.messaging.outgoing.operativt-uppgiftslager-status-notification.connector=smallrye-kafka
mp.messaging.outgoing.operativt-uppgiftslager-status-notification.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Kafka broker configuration
# %dev.kafka.bootstrap.servers=127.0.0.1:9092
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}

quarkus.kafka.devservices.enabled=true
# quarkus.log.category."org.apache.kafka.clients.NetworkClient".level=ERROR